services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    build:
      context: ./back
    ports:
      - 3000:3000
    env_file:
      - ./back.env
    volumes:
      - ./back:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: easydevs
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: easydevs
    ports:
      - 5432:5432
    volumes:
      - ./back/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U easydevs" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
