services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.front
    ports:
      - 5173:5173
    volumes:
      - ./front:/app # Synchronisation du code local
      - /app/node_modules

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./.env.back
    volumes:
      - ./back:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: easydevs
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: easydevs
    ports:
      - 5432:5432
    volumes:
      - ./back/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U easydevs" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
