services:    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.back
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
  db:
    image: postgres:alpine
    env_file:
      - ./.env.back  # On force le fichier .env.back ici
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ../db-init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easydevs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-db: