# Utilise une image Node.js légère
FROM node:18-alpine

# Crée un répertoire de travail
WORKDIR /app

# Copie uniquement les fichiers nécessaires pour l'installation
COPY package.json package-lock.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers
VOLUME [ "/app" ]

# Expose le port utilisé par Vite
EXPOSE 5173

# Commande par défaut pour le développement
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--mode", "docker"]